### ISSUE TITLE
Tenary aka Elvis expression in CFSCRIPT

### ISSUE THREAD

**Issue by remy-tiitre** [cfparser/cfparser#32]
I don't think it has been correctly defined in parser. Didn't analyze it in antlr but I have parsing erros in code like this:

someStruct = {
    someVariable = someExpression ? someExpression2 : someExpression3
}

Its also possible that implicit struct might have issues with tenary expressions. But Elvis expression has been defined as:

elvisExpression:
	unaryExpression QUESTIONMARK COLON baseOrTernaryExpression;

First, I think it should have <assoc=right> and baseOrTenaryExpression should be also between the QUESTIONMARK and COLON and in both cases the baseOrTenaryExpression is optional.

Will try it out when I have more time.

**Comment by denuno** [comment]
Keep in mind that this is handled differently on ACF than Lucee.. I have a patch for ternary stuff that I haven't applied because it only works on Lucee (can't remember if it's this issue or not), but I'm kind of thinking that be be really good, we need two parsers, one for ACF and one for Lucee.

If you've found something that works in both engines, but that the parser thinks is an error, it should get fixed, but I'm not sure how much we should cater to either engine in the cases where syntax is good on one and bad on the other. :-/

**Comment by ryaneberly** [comment]
The conditional ternary operator is under the compareExpression.  And the binary elvis operator is elvisOperator under the baseExpression.

I think the tenary operator should moved from compareExpression to  under baseExpression as well.

**Comment by ryaneberly** [comment]
(strike line 424 in CFSCRIPTParser.g4)

**Comment by ryaneberly** [comment]
looks good.  thanks.

**Comment by remy-tiitre** [comment]
Most of the parsing errors were fixed with this patch. There still seems to be at least one corner case. Not sure if its different in Lucee.

new some.path.to.cfc.component.cfcComponent(argument = "someValue",
	componentArguments = {
		argument1 = localVariableName,
		argument2 = isLocalVariableBoolean ? true : false,
	}
);

When I remove tenary, it works.
